version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - wget https://golang.org/dl/go1.18.linux-amd64.tar.gz
      - tar -xzf go1.18.linux-amd64.tar.gz
      - mv go /usr/local  
      - export GOROOT=/usr/local/go 
      - export PATH=$GOPATH/bin:$GOROOT/bin:$PATH 
      - go version 
      - yum install asciidoctor -y
      - mkdir $HOME/src
      - cd $HOME/src
      - git clone https://github.com/gohugoio/hugo.git
      - cd hugo
      - go mod download github.com/yuin/goldmark
      - go install --tags extended
    finally:
      - echo Installation done
  build:
    commands:
      - echo Building...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - hugo --quiet
      - aws s3 sync --delete docs/ s3://trmccormick.com
      - aws cloudfront create-invalidation --distribution-id E31546NI4VOO5F --paths '/*'
    finally:
      - echo Build finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/docs
  discard-paths: no