version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install curl -y
      - yum install asciidoctor -y
      - curl -s -L https://github.com/gohugoio/hugo/releases/download/v0.87.0/hugo_0.87.0_Linux-64bit.deb -o hugo.deb
      - dpkg -i hugo.deb
    finally:
      - echo Installation done
  build:
    commands:
      - echo Building...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - GIT_CONFIG_NOSYSTEM=true hugo
      - aws s3 sync --delete docs/ s3://trmccormick.com
      - aws cloudfront create-invalidation --distribution-id E31546NI4VOO5F --paths '/*'
    finally:
      - echo Build finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/docs
  discard-paths: no