version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum install golang-1.16 -y
      - yum install curl -y
      - yum install asciidoctor -y
      - mkdir $HOME/src
      - cd $HOME/src
      - git clone https://github.com/gohugoio/hugo.git
      - cd hugo
      - go install --tags extended -y
    finally:
      - echo Installation done
  build:
    commands:
      - echo Building...
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - hugo --quiet
      - aws s3 sync --delete docs/ s3://trmccormick.com
      - aws cloudfront create-invalidation --distribution-id E31546NI4VOO5F --paths '/*'
    finally:
      - echo Build finished
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR/docs
  discard-paths: no